

/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_joystick.h"
#include "sc_joystick_type.h"
#include "sc_speed.h"
#include "sc_speed_type.h"



/* signal configuration */
/*
* description: Joystick x and y values for controlling the car manually
* indriver: 0
* name: so_joystick
* onDataError: 0
* onDataUpdate: ev_joystick_onData
* outdriver: 0
* resource: None
* shortname: joystick
* signalclass: sc_joystick
* signalpool: sp_common
*/


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_joystick_updTasks = { tsk_control };
 

static const SC_JOYSTICK_cfg_t SO_JOYSTICK_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_joystick_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_joystick_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_joystick */


/* signal data */

SC_JOYSTICK_t SO_JOYSTICK_signal= 
{
   /* init value    */  SC_JOYSTICK_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_JOYSTICK_cfg,
}; /* data so_joystick */

/* signal configuration */
/*
* description: Targetspeed defined by the user
* indriver: 0
* name: so_targetspeed
* onDataError: 0
* onDataUpdate: ev_targetspeed_onData
* outdriver: 0
* resource: None
* shortname: targetspeed
* signalclass: sc_speed
* signalpool: sp_common
*/


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_targetspeed_updTasks = { tsk_io };
 

static const SC_SPEED_cfg_t SO_TARGETSPEED_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_targetspeed_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_targetspeed_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_targetspeed */


/* signal data */

SC_SPEED_t SO_TARGETSPEED_signal= 
{
   /* init value    */  SC_SPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_TARGETSPEED_cfg,
}; /* data so_targetspeed */



void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_JOYSTICK_incAge( &SO_JOYSTICK_signal, tick); 
   RTE_SC_SPEED_incAge( &SO_TARGETSPEED_signal, tick); 
   
}


