
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */

/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_joystick.h"
#include "sc_speed.h"



/*
* description: Joystick x and y values for controlling the car manually
* indriver: 0
* name: so_joystick
* onDataError: 0
* onDataUpdate: ev_joystick_onData
* outdriver: 0
* resource: None
* shortname: joystick
* signalclass: sc_joystick
* signalpool: sp_common
*/
extern SC_JOYSTICK_t SO_JOYSTICK_signal;


/*
* description: Targetspeed defined by the user
* indriver: 0
* name: so_targetspeed
* onDataError: 0
* onDataUpdate: ev_targetspeed_onData
* outdriver: 0
* resource: None
* shortname: targetspeed
* signalclass: sc_speed
* signalpool: sp_common
*/
extern SC_SPEED_t SO_TARGETSPEED_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

#endif