
/*
 * Filename: swc_control.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_CONTROL
#define _H_DEFINE_SWC_CONTROL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_CONTROL_INCLUDES */

/* USER CODE END SWC_CONTROL_INCLUDES */



/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */


/*
* component: swc_control
* cycletime: 0
* description: Runnable which translates joystick position into targetspeed for engines
* events: ev_joystick_onData
* name: CONTROL_calcControl_run
* shortname: calcControl
* signalIN: so_joystick
* signalOUT: so_targetspeed
* task: tsk_control
*/
void CONTROL_calcControl_run(RTE_event ev);


#endif