
/*
 * Filename: swc_engine.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_ENGINE
#define _H_DEFINE_SWC_ENGINE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_ENGINE_INCLUDES */

/* USER CODE END SWC_ENGINE_INCLUDES */



/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */


/*
* component: swc_engine
* cycletime: 100
* description: Runnable which sets the speed of the engine
* events: 
* name: ENGINE_setEngine_run
* shortname: setEngine
* signalIN: so_targetspeed
* signalOUT: 
* task: tsk_io
*/
void ENGINE_setEngine_run(RTE_event ev);

/*
* component: swc_engine
* cycletime: 0
* description: Runnable that sets the engine brake light
* events: 
* name: ENGINE_setBrakeLight_run
* shortname: setBrakeLight
* signalIN: so_targetspeed
* signalOUT: 
* task: tsk_io
*/
void ENGINE_setBrakeLight_run(RTE_event ev);


#endif