

/*
 * Filename: swc_joystick.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_joystick.h"



/* USER CODE START SWC_JOYSTICK_INCLUDE */
#include "joystick.h"
/* USER CODE END SWC_JOYSTICK_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_JOYSTICK_USERDEFINITIONS */

/* USER CODE END SWC_JOYSTICK_USERDEFINITIONS */



/*
* component: swc_joystick
* cycletime: 10
* description: Runnable for the incoming joystick x and y values
* events: 
* name: JOYSTICK_readJoystick_run
* shortname: readJoystick
* signalIN: 
* signalOUT: so_joystick
* task: tsk_io
*/
void JOYSTICK_readJoystick_run(RTE_event ev){
	
	/* USER CODE START JOYSTICK_readJoystick_run */
    SC_JOYSTICK_data_t gasPedal = SC_JOYSTICK_INIT_DATA;
    
    JOYSTICK_ReadPosition(&gasPedal.x,&gasPedal.y);
    RTE_SC_JOYSTICK_set(&SO_JOYSTICK_signal, gasPedal);
    RTE_SC_JOYSTICK_pullPort(&SO_JOYSTICK_signal);
    /* USER CODE END JOYSTICK_readJoystick_run */
}

/* USER CODE START SWC_JOYSTICK_FUNCTIONS */

/* USER CODE END SWC_JOYSTICK_FUNCTIONS */

